files:
  - source: /src/i18n/locales/en-US.json
    translation: /src/i18n/locales/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        nl-BE: nl-BE
        pt-BR: pt-BR
        zh-CN: zh-HANS
        zh-TW: zh-HANT
