name: Open empty issue
description: For everything that's neither a feature request, nor a bug
body:
  - type: markdown
    attributes:
      value: |
        1. Please remember that if you are logging a bug for some service that has *stopped working*, please log the bug [here](https://github.com/ferdium/fedium-recipes/issues)
        2. If you are requesting support for a new service in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
        3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to old recipes.
        4. Please consider supporting Ferdium!
          👉  https://github.com/sponsors/ferdium
          👉  https://opencollective.com/ferdium/donate

  - type: textarea
    attributes:
      label: "Your issue"
      description: "Describe your issue"
    validations:
      required: true
