name: Bug Report
description: Report an Ferdium bug
title: "[Bug]: "
labels: ["bug :beetle:"]
body:
- type: markdown
  attributes:
    value: |
      1. Please remember that if you are logging a bug for some service that has *stopped working*, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
      2. If you are requesting support for a new service in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/issues/new/choose)
      3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to old recipes.
      4. Please fill our form below, this way we can analyse and fix the problem as fast as possible.
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
        required: true
      - label: I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
        required: true
      - label: I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.
        required: true
- type: input
  attributes:
    label: Ferdium Version
    description: What version of Ferdium are you using?
    placeholder: 5.6.3
  validations:
    required: true
- type: input
  attributes:
    label: Recipe Name
    description: What is the name of the specific recipe you are using?
    placeholder: 1.0.0
  validations:
    required: true
- type: input
  attributes:
    label: Recipe Version
    description: What version of the specific recipe are you using?
    placeholder: 1.0.0
  validations:
    required: true
- type: input
  attributes:
    label: Last Known working version of the recipe
    description: What is the last version of the recipe this worked in, if applicable?
    placeholder: 1.0.0
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Explain to us how we can reproduce your bug on our computer
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear description of what actually happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem. You can simply drag and drop any image file into the editor to add it to the report
- type: textarea
  attributes:
    label: Additional Information
    description: If your problem needs further explanation, or if the issue you're seeing cannot be reproduced in a gist, please add more information here.
