#!/bin/sh

FILE_NAME="$(dirname "$0")/_/husky.sh"

# Conditionally invoke so as to avoid running npm commands if this is a clean checkout (ie before installing npm modules)
if [ -f $FILE_NAME ]; then
  . $FILE_NAME

  npx --no-install commitlint --edit "$1"
fi
